[package]
name = "lam-daemon"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
build = "build.rs"

[[bin]]
name = "lam-daemon"
path = "src/main.rs"

[[bin]]
name = "lam-integrity-check"
path = "src/bin/integrity_check.rs"

[dependencies]
device-config = { workspace = true }
hid-transport = { workspace = true }
tokio = { workspace = true }
tokio-udev = { workspace = true }
futures = { workspace = true }
zbus = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
nix = { workspace = true }
serde = { workspace = true }
serde_yaml = { workspace = true }
serde_json = { workspace = true }
reqwest = { workspace = true }
sha2 = { workspace = true }
zip = { workspace = true }
flate2 = { workspace = true }
realfft = { workspace = true }

[dev-dependencies]
lam-hidraw-helper = { workspace = true }
tempfile = "3"
