// Watches PipeWire/PulseAudio client events and activates per-app EQ overrides.
//
// Uses a persistent libpulse context (rather than `pactl` subprocesses) for
// both event subscription and client introspection.  The subprocess approach
// caused a self-feeding event loop: each `pactl list clients` invocation
// created a new PA client, which generated "client" subscribe events, which
// triggered another invocation — indefinitely.  A single persistent context
// avoids this because introspection queries reuse the existing connection and
// produce no new client-connect events.

use std::collections::HashMap;
use std::path::{Path, PathBuf};
use std::sync::atomic::{AtomicBool, Ordering};
use std::sync::Arc;

use libpulse_binding as pulse;
use pulse::callbacks::ListResult;
use pulse::context::subscribe::{Facility, InterestMaskSet};
use pulse::context::{Context, FlagSet, State};
use pulse::mainloop::standard::{IterateResult, Mainloop};

use tokio::sync::{broadcast, Mutex};
use tracing::{info, warn};

use device_config::codec::FieldValue;

use crate::audio::AudioSetup;
use crate::eq::settings::{
    load_eq_settings, AppMatcher, Channel, ChannelEqSettings, EqBackend, EqSettings,
};
use crate::eq_manager::{self as eq_manager, EqRuntime};
use crate::state::{AppState, DeviceCommand, SignalEvent};

// ── Client snapshot ───────────────────────────────────────────────────────────

#[derive(Clone)]
struct PwClient {
    name: String,
    binary: String,
    pid: u32,
}

// ── Matcher ───────────────────────────────────────────────────────────────────

fn matches(client: &PwClient, matcher: &AppMatcher) -> bool {
    match matcher {
        AppMatcher::Stream { name } => client.name == *name,
        AppMatcher::Executable { path } => {
            let base = Path::new(path)
                .file_name()
                .and_then(|n| n.to_str())
                .unwrap_or(path.as_str());
            client.binary == base
        }
        AppMatcher::SteamGame { app_id } => steam_app_id_for_pid(client.pid) == Some(*app_id),
    }
}

fn steam_app_id_for_pid(pid: u32) -> Option<u32> {
    let env = std::fs::read_to_string(format!("/proc/{pid}/environ")).ok()?;
    env.split('\0')
        .find_map(|var| var.strip_prefix("SteamAppId=")?.parse().ok())
}

// ── PA client watcher ─────────────────────────────────────────────────────────

/// Spawn a blocking thread that maintains a PA context and sends snapshots of
/// the live client list whenever it changes.  Returns a `watch::Receiver` that
/// always holds the latest snapshot.
fn start_pa_watcher() -> tokio::sync::watch::Receiver<Vec<PwClient>> {
    let (tx, rx) = tokio::sync::watch::channel(vec![]);
    std::thread::Builder::new()
        .name("lam-pa-watcher".into())
        .spawn(move || pa_watcher_thread(tx))
        .expect("failed to spawn PA watcher thread");
    rx
}

/// Runs a libpulse standard mainloop in a dedicated thread.
/// Subscribes to CLIENT events and sends a full client snapshot via `tx`
/// whenever the client list changes.  Both subscription and introspection use
/// the same persistent PA context, so no new client-connect events are
/// generated by the queries themselves.
fn pa_watcher_thread(snapshot_tx: tokio::sync::watch::Sender<Vec<PwClient>>) {
    let mut mainloop = match Mainloop::new() {
        Some(ml) => ml,
        None => {
            warn!("stream monitor: PA mainloop init failed");
            return;
        }
    };

    let mut context = match Context::new(&mainloop, "lam-stream-monitor") {
        Some(ctx) => ctx,
        None => {
            warn!("stream monitor: PA context init failed");
            return;
        }
    };

    if context.connect(None, FlagSet::NOAUTOSPAWN, None).is_err() {
        warn!("stream monitor: PA connect failed");
        return;
    }

    // Iterate (blocking) until the context transitions to Ready or fails.
    loop {
        match mainloop.iterate(true) {
            IterateResult::Quit(_) | IterateResult::Err(_) => return,
            IterateResult::Success(_) => {}
        }
        match context.get_state() {
            State::Ready => break,
            State::Failed | State::Terminated => {
                warn!("stream monitor: PA context failed to connect");
                return;
            }
            _ => {}
        }
    }

    // Subscribe to client events.  Any change in the client list sets
    // `needs_refresh`, which triggers a full `get_client_info_list` in the
    // main loop below.
    context.subscribe(InterestMaskSet::CLIENT, |_| {});

    let needs_refresh = Arc::new(AtomicBool::new(true));
    {
        let flag = Arc::clone(&needs_refresh);
        context.set_subscribe_callback(Some(Box::new(move |facility, _, _| {
            if facility == Some(Facility::Client) {
                flag.store(true, Ordering::Relaxed);
            }
        })));
    }

    // `pending` is written by the `get_client_info_list` callback (on the
    // mainloop thread, during `iterate()`) and read by the loop below
    // immediately after `iterate()` returns.  The Mutex is never contended —
    // all access is single-threaded with the standard mainloop — but is
    // required for `Send`/`Sync` in the `'static` closure.
    let pending: Arc<std::sync::Mutex<Option<Vec<PwClient>>>> =
        Arc::new(std::sync::Mutex::new(None));

    loop {
        match mainloop.iterate(false) {
            IterateResult::Quit(_) | IterateResult::Err(_) => return,
            IterateResult::Success(_) => {}
        }

        match context.get_state() {
            State::Failed | State::Terminated => {
                warn!("stream monitor: PA context disconnected");
                return;
            }
            _ => {}
        }

        // Drain any completed introspect result and send it as a new snapshot.
        if let Some(clients) = pending.lock().unwrap().take() {
            let _ = snapshot_tx.send(clients);
        }

        // Queue a full client list refresh when signalled by the subscribe cb.
        if needs_refresh.swap(false, Ordering::Relaxed) {
            let pending_cb = Arc::clone(&pending);
            let mut buf = Vec::<PwClient>::new();

            context
                .introspect()
                .get_client_info_list(move |result| match result {
                    ListResult::Item(info) => {
                        let name = info
                            .proplist
                            .get_str("application.name")
                            .or_else(|| info.name.as_deref().map(str::to_owned))
                            .unwrap_or_default();
                        // Skip PA/PW internals and our own monitor client.
                        if name.starts_with("pipewire")
                            || name.starts_with("PulseAudio")
                            || name == "lam-stream-monitor"
                        {
                            return;
                        }
                        let binary = info
                            .proplist
                            .get_str("application.process.binary")
                            .unwrap_or_default();
                        let pid = info
                            .proplist
                            .get_str("application.process.id")
                            .and_then(|s| s.parse().ok())
                            .unwrap_or(0);
                        buf.push(PwClient { name, binary, pid });
                    }
                    ListResult::End => {
                        *pending_cb.lock().unwrap() = Some(std::mem::take(&mut buf));
                    }
                    ListResult::Error => {
                        *pending_cb.lock().unwrap() = Some(vec![]);
                    }
                });
            // The returned Operation is dropped here; pa_operation_unref does
            // NOT cancel the operation — the callback still fires.
        }

        // Yield to avoid busy-looping when there are no pending PA events.
        std::thread::sleep(std::time::Duration::from_millis(20));
    }
}

// ── Override application ──────────────────────────────────────────────────────

async fn check_and_apply(
    base_dir: &Path,
    settings: &EqSettings,
    audio_shared: &Arc<Mutex<Option<AudioSetup>>>,
    eq_rt: &Arc<Mutex<EqRuntime>>,
    app_state: &Arc<Mutex<AppState>>,
    active: &mut HashMap<Channel, Option<String>>,
    clients: &[PwClient],
) {
    let hw_ctx = {
        let st = app_state.lock().await;
        eq_manager::build_hw_eq_context(&st)
    };

    for (channel, ch_settings) in [
        (Channel::Media, &settings.media),
        (Channel::Chat, &settings.chat),
    ] {
        let is_hw_backend = matches!(ch_settings.backend, EqBackend::Hardware);
        if is_hw_backend
            && ch_settings
                .app_overrides
                .iter()
                .all(|o| o.hw_preset_idx.is_none())
        {
            continue;
        }
        if ch_settings.app_overrides.is_empty() {
            continue;
        }

        let matched_ov = ch_settings
            .app_overrides
            .iter()
            .find(|ov| clients.iter().any(|c| matches(c, &ov.matcher)));

        let matched_key: Option<String> = matched_ov.map(|ov| {
            if let Some(idx) = ov.hw_preset_idx {
                format!("hw:{idx}")
            } else {
                ov.preset.clone()
            }
        });

        let currently = active.get(&channel).and_then(|v| v.as_deref());

        match (matched_key.as_deref(), currently) {
            (Some(k), Some(c)) if k == c => {}
            (None, None) => {}
            (Some(key), _) => {
                info!("stream monitor: {channel} → override '{key}'");
                let ov = matched_ov.unwrap();
                if let Some(idx) = ov.hw_preset_idx {
                    if let Some(ctx) = &hw_ctx {
                        let values = std::collections::HashMap::from([(
                            "eq_preset".to_string(),
                            FieldValue::U8(idx),
                        )]);
                        let _ = ctx
                            .cmd_tx
                            .send(DeviceCommand::WriteApi {
                                api_name: "selected_eq_preset".into(),
                                values,
                            })
                            .await;
                    }
                } else if !is_hw_backend {
                    let mut ovr = ch_settings.clone();
                    ovr.preset = ov.preset.clone();
                    ovr.enabled = true;
                    eq_manager::apply_channel_eq(
                        &ovr,
                        channel,
                        base_dir,
                        audio_shared,
                        eq_rt,
                        hw_ctx.as_ref(),
                    )
                    .await;
                }
                active.insert(channel, Some(key.to_owned()));
            }
            (None, Some(prev)) => {
                info!("stream monitor: {channel} → restoring default");
                if !prev.starts_with("hw:") && is_hw_backend {
                    // Software override on hw-backend — focus_monitor owns this, skip.
                } else {
                    restore_channel(
                        ch_settings,
                        channel,
                        base_dir,
                        audio_shared,
                        eq_rt,
                        hw_ctx.as_ref(),
                    )
                    .await;
                }
                active.insert(channel, None);
            }
        }
    }
}

async fn restore_channel(
    ch: &ChannelEqSettings,
    channel: Channel,
    base_dir: &Path,
    audio_shared: &Arc<Mutex<Option<AudioSetup>>>,
    eq_rt: &Arc<Mutex<EqRuntime>>,
    hw_ctx: Option<&eq_manager::HwEqContext>,
) {
    if ch.enabled {
        eq_manager::apply_channel_eq(ch, channel, base_dir, audio_shared, eq_rt, hw_ctx).await;
    } else {
        eq_manager::disable_channel_eq(channel, audio_shared, eq_rt, hw_ctx).await;
    }
}

// ── Entry point ───────────────────────────────────────────────────────────────

pub async fn run(
    settings_base_dir: PathBuf,
    audio_shared: Arc<Mutex<Option<AudioSetup>>>,
    eq_rt: Arc<Mutex<EqRuntime>>,
    app_state: Arc<Mutex<AppState>>,
    mut signal_rx: broadcast::Receiver<SignalEvent>,
) {
    let mut eq_settings = load_eq_settings(&settings_base_dir);
    let mut active: HashMap<Channel, Option<String>> = HashMap::new();

    let has_overrides =
        |s: &EqSettings| !s.media.app_overrides.is_empty() || !s.chat.app_overrides.is_empty();

    // Start the PA watcher only when there are overrides to evaluate.
    // If the user later adds overrides via EQChanged, the watcher is started lazily.
    let mut client_rx: Option<tokio::sync::watch::Receiver<Vec<PwClient>>> =
        has_overrides(&eq_settings).then(start_pa_watcher);

    loop {
        tokio::select! {
            result = async {
                match client_rx.as_mut() {
                    Some(rx) => rx.changed().await,
                    None => std::future::pending().await,
                }
            } => {
                if result.is_ok() {
                    if let Some(rx) = &client_rx {
                        let clients = rx.borrow().clone();
                        check_and_apply(
                            &settings_base_dir,
                            &eq_settings,
                            &audio_shared,
                            &eq_rt,
                            &app_state,
                            &mut active,
                            &clients,
                        )
                        .await;
                    }
                }
            }

            event = signal_rx.recv() => {
                match event {
                    Ok(SignalEvent::EQChanged { json }) => {
                        if let Ok(s) = serde_json::from_str::<EqSettings>(&json) {
                            eq_settings = s;
                            if client_rx.is_none() && has_overrides(&eq_settings) {
                                client_rx = Some(start_pa_watcher());
                            }
                            if let Some(rx) = &client_rx {
                                let clients = rx.borrow().clone();
                                check_and_apply(
                                    &settings_base_dir,
                                    &eq_settings,
                                    &audio_shared,
                                    &eq_rt,
                                    &app_state,
                                    &mut active,
                                    &clients,
                                )
                                .await;
                            }
                        }
                    }
                    Err(broadcast::error::RecvError::Closed) => break,
                    _ => {}
                }
            }
        }
    }
}

// ── Tests ─────────────────────────────────────────────────────────────────────

#[cfg(test)]
mod tests {
    use super::*;
    use crate::eq::settings::AppMatcher;

    fn client(name: &str, binary: &str, pid: u32) -> PwClient {
        PwClient {
            name: name.to_owned(),
            binary: binary.to_owned(),
            pid,
        }
    }

    #[test]
    fn stream_matcher_matches_by_name() {
        let c = client("Spotify", "spotify", 1234);
        assert!(matches(
            &c,
            &AppMatcher::Stream {
                name: "Spotify".into()
            }
        ));
        assert!(!matches(
            &c,
            &AppMatcher::Stream {
                name: "Firefox".into()
            }
        ));
    }

    #[test]
    fn executable_matcher_uses_basename() {
        let c = client("Firefox", "firefox", 1234);
        assert!(matches(
            &c,
            &AppMatcher::Executable {
                path: "/usr/bin/firefox".into()
            }
        ));
        assert!(matches(
            &c,
            &AppMatcher::Executable {
                path: "firefox".into()
            }
        ));
        assert!(!matches(
            &c,
            &AppMatcher::Executable {
                path: "/usr/bin/spotify".into()
            }
        ));
    }

    #[test]
    fn steam_matcher_no_pid_returns_false() {
        let c = client("GameApp", "game", 0);
        assert!(!matches(&c, &AppMatcher::SteamGame { app_id: 730 }));
    }
}
