[package]
name = "lam-hidraw-helper"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
build = "build.rs"

[lib]
name = "lam_hidraw_helper"
path = "src/lib.rs"

[[bin]]
name = "lam-hidraw-helper"
path = "src/main.rs"

[[bin]]
name = "lam-hidraw-helper-mock"
path = "src/mock_main.rs"

[dependencies]
tokio = { workspace = true }
nix = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }

[dev-dependencies]
tempfile = "3"
